- app/Services/Post.php
Set a default article type of 'article', or if present, use the gallery type identifier from the Catfish JSON response.
> Set article type

- app/Services/Sync.php
- app/panels.php
you can now sync articles from either shortlist or stylist by putting in the site url in the options
> you now change the url of categories you want to sync

- app/Services/Post.php
Prevents issue where default user is not used
> If email address is empty, load default user

- app/Services/Post.php
- app/Services/Widgets/Html.php
- app/Services/Widgets/Video.php
- tests/features/bootstrap/PostContext.php
- tests/features/bootstrap/SyncContext.php
- tests/features/post.feature
* Fixed a few issues with the unittests being out of date with code changes
* More tolerant of varied input data for scraping of FB videos
> FB Videos were not being imported correctly

- tests/features/bootstrap/PostContext.php
- tests/features/post.feature
Created a new test that checks the number of images present in the imported article.
> Check post has images

- app/Services/Sitemap.php
- app/Services/Widgets/Html.php
Clean up duplicate code in Html class, add comments and fix errors in testing with Sitemap class.
> Misc fixes to html dom parser

- app/Services/Post.php
2.2x speed increase in importer as measured by the Post tests in xdebug. The work on the Widgets refactor only eked out another .3x increase for arguably more verbose code so I've stashed that.
> Performance improvements - Refactored Posts class

- app/Services/Post.php
- app/Services/Sync.php
- app/Services/Worker.php
- app/cli.php
- tests/features/bootstrap/FeatureContext.php
- tests/features/bootstrap/PostContext.php
- tests/features/bootstrap/SyncContext.php
- tests/features/sync.feature
Clear automated_testing posts before and after each test feature and with given function
https://trello.com/c/J7nEbLKw/30-3-consider-process-creating-consistent-state-to-run-tests-against
> Create a consistent test environment

- .gitignore
- README.md
- app/Services/Post.php
- app/Services/Sitemap.php
- app/Services/Sync.php
- app/cli.php
- app/hooks.php
- app/routes.php
- composer.json
- herbert.config.php
- tests/features/bootstrap/SitemapContext.php
- tests/features/bootstrap/SyncContext.php
- tests/features/sync.feature
Design and implement a cronjob to scan for updated content
> Scan for updated content

- .gitignore
- README.md
- app/Services/Post.php
- app/Services/Sitemap.php
- app/Services/Sync.php
- app/cli.php
- app/hooks.php
- app/routes.php
- composer.json
- herbert.config.php
- tests/features/bootstrap/SitemapContext.php
- tests/features/bootstrap/SyncContext.php
- tests/features/sync.feature
Minor bug reported to Will where the new posts didn't show on the Recently Imported listings.
> Imported posts don't show on the Recent Imports page

- app/Services/Sync.php
- app/Services/Worker.php
- app/cli.php
- composer.json
Pass handled errors to BugSnag directly as well as unhandled errors.
> Direct Bugsnag error reporting for handled errors

- README.md
- app/Services/Queue.php
- app/Services/SitemapParser.php
- app/Services/Sync.php
- app/cli.php
New setting to allow for different target URLs when importing.
> Setup content importer for Stylist.co.uk

- README.md
- app/Services/Sync.php
Complete and tested Importer and Updated Posts Scanner.
> Complete and tested Importer and Updated Posts Scanner

- app/Services/Post.php
- app/Services/Sync.php
- app/Services/Widget.php
- app/Services/Widgets/Html.php
Correctly imports Inline image galleries: https://trello.com/c/R3REw3EP/81-in-page-gallery-widget-not-being-imported
> Add support for Inline gallery to importer

- app/Services/SiteMap.php
- app/Services/Sync.php
- app/api.php
- app/cli.php
- cron-repeat.sh
few performance/functionality issues fixed.
> Fix file get html overflow

- README.md
- app/Controllers/SyncController.php
- app/Services/Category.php
- app/Services/Post.php
- app/Services/Widgets/Html.php
- app/custom-fields/acf.php
Fixed missing keys. 
Most of the style changes are reformatting changes. Post.php should have actually important stuff.
> fixed missing keys in importer acf

- app/Api.php
- app/Services/Category.php
- app/Services/Fetch.php
- app/Services/Post.php
- app/Services/SiteMap.php
- app/Services/Widget.php
- app/cli.php
Add one App class which is de facto cascade for all import options. 
Changed file_get_contents to custom curl, so we could use origin domain instead of main domain. 
Removed not needed reporting
> Catfish speedup

- app/Services/Fetch.php
- app/Services/Post.php
- app/Services/Widget.php
Added category cache to catfish importer to minimise amount of requests to live server, this same removing some of the issues with fetching items.
> added cache and fixed issue with wrong replace on some urls

- app/Services/Widget.php
- app/Services/Widgets/HorizontalRule.php
> Import horizontal-rule as divider

- app/Services/Post.php
- app/Services/Widgets/Video.php
So I think this is probably not in the right place or anything... not entirely sure what I was doing and have had a fair few problems with my vagrant and database, so need to check on the other video formats! but _fairly_ sure the youtube one is correct...
?
> initial work to convert video headers into a first embed widget

- README.md
- app/Exception/AddressUnavailableException.php
- app/Exception/CatfishException.php
- app/Exception/ImageUnavailable.php
- app/Exception/WrongDataFormatException.php
- app/Services/WPErrorToException.php
- app/Services/Widget.php
- app/Services/Widgets/Embed.php
- app/Services/Widgets/Html.php
- app/Services/Widgets/InlineImage.php
Added html galleries support
Fixed error where updating post could leave extra widgets
Fixed error where fields were not saved properly and did not show in editor
Improved widget merging
Improved html parsing (we can extract images from content)
More logging again
Probably some stuff I don't remember now of :)
> Html Gallery and Html parsing
